### ISSUE TITLE
label:bug 使用报错

### ISSUE THREAD

**Issue by 502milk** [MX233/Mirai-MCPingPlugin#3]
ping mod服务出现（ip是mcbbs随便找的mc.maryt.world:3501
```
2021-07-30 10:34:05 W/stderr: Exception in thread "Thread-32" java.lang.IllegalArgumentException: Illegal base64 character a
2021-07-30 10:34:05 W/stderr:   at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
2021-07-30 10:34:05 W/stderr:   at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
2021-07-30 10:34:05 W/stderr:   at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
2021-07-30 10:34:05 W/stderr:   at tax.cute.mcpingplugin.JETypeset.getTypeset(JETypeset.java:47)
2021-07-30 10:34:05 W/stderr:   at tax.cute.mcpingplugin.MCJEPingThread.ping(MCJEPingThread.java:50)
2021-07-30 10:34:05 W/stderr:   at tax.cute.mcpingplugin.MCJEPingThread.run(MCJEPingThread.java:32)
```

**Comment by Pmaru-top** [comment]
经检查,此服务器返回了分行的base64导致无法解析
![`EV 26ZSPNQOO(`ZWTZ3KE7](https://user-images.githubusercontent.com/78346594/127634919-8ded5cb6-222d-496f-afed-abb5111b29fd.png)
修复方法
![KZEYKCO 2Y4XI 6I)FPU`_P](https://user-images.githubusercontent.com/78346594/127635031-f8f130f7-5fd7-4be9-9bb1-e1b5453af9c8.png)
已修复发布在[v2.0-Beta.2-lib](https://github.com/MX233/Mirai-MCPingPlugin/releases/tag/v2.0-Beta.2-lib)
