### ISSUE TITLE
/data/MCPing 下无Pin码文件

### ISSUE THREAD

**Issue by Cicini** [MX233/Mirai-MCPingPlugin#5]
版本为刚刚发的Beta.3
MCPing下是空文件夹
Mirai版本2.7-M2

**Comment by Cicini** [comment]
后台无任何报错

**Comment by Pmaru-top** [comment]
~~我自己测试了下没问题~~
~~懒得排查了~~改了下V2.0-Beta.3增加了控制台操作,砍了Pin码验证
重新下载安装 V2.0-Beta.3 即可
然后看README来操作

**Comment by Cicini** [comment]
怪哦
```
2021-08-24 12:08:54 I/MCPing: [MCPing]github URL: https://github.com/MX233/Mirai-MCPingPlugin
2021-08-24 12:08:54 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading MCPing
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:122)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:208)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: net.mamoe.mirai.console.permission.PermissionRegistryConflictException: Conflicting Permission registry. new: PermissionImpl(id=tax.cute.mcpingplugins:*, description='The base permission', parent=PermissionImpl(id=*:*, description='The root permission', parent=<self>)), existing: PermissionImpl(id=tax.cute.mcpingplugins:*, description='The base permission', parent=PermissionImpl(id=*:*, description='The root permission', parent=<self>))
        at net.mamoe.mirai.console.internal.permission.AbstractConcurrentPermissionService.register(AbstractConcurrentPermissionService.kt:31)
        at net.mamoe.mirai.console.permission.PermissionService.register$default(PermissionService.kt:98)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal$parentPermission$2.invoke(JvmPluginInternal.kt:48)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal$parentPermission$2.invoke(JvmPluginInternal.kt:47)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.getParentPermission(JvmPluginInternal.kt:47)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:109)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        ... 39 more

2021-08-24 12:08:54 I/MCPing: [MCPing]Disable
```

**Comment by Cicini** [comment]
以及刚刚在重新放插件的时候
发现旧版的Beta3在MCL根目录生成了
```
data\MCPing\Betypeset.txt
data\MCPing\Config.json
data\MCPing\Pin.txt
data\MCPing\typeset.txt
```
没有生成在对于目录里，而是生成了包含目录的文件名的对应文件
文件根据修改时间可以确定是之前的Beta3放出的
系统Debian 10 64x

**Comment by Cicini** [comment]
经测试新版Beta3出现相同情况

> 以及刚刚在重新放插件的时候
> 发现旧版的Beta3在MCL根目录生成了
> 
> ```
> data\MCPing\Betypeset.txt
> data\MCPing\Config.json
> data\MCPing\Pin.txt
> data\MCPing\typeset.txt
> ```
> 
> 没有生成在对于目录里，而是生成了包含目录的文件名的对应文件
> 文件根据修改时间可以确定是之前的Beta3放出的
> 系统Debian 10 64x

新版Beta3存在相同情况

**Comment by Pmaru-top** [comment]
[MCPing2.1](https://github.com/MX233/Mirai-MCPingPlugin/releases/tag/v2.1) 支持控制台操作以及

更新配置文件路径获取方式了

**Comment by Pmaru-top** [comment]
修复完成发通知11天无回复当无其他问题,关issue了
